"""create change_log

Revision ID: 043cf8cd5aa2
Revises: 633a26b2fd66
Create Date: 2026-03-05 16:04:06.619731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043cf8cd5aa2'
down_revision = '633a26b2fd66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('limit_each', sa.Integer(), nullable=False),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('total_targeted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_logs_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_logs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_logs_status'))
        batch_op.drop_index(batch_op.f('ix_campaign_logs_created_by_user_id'))

    op.drop_table('campaign_logs')
    # ### end Alembic commands ###
