"""add user profile fields and student exam numbers

Revision ID: 2733f645d0be
Revises: 90f6436b767c
Create Date: 2026-10-10 21:45:20.627218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2733f645d0be'
down_revision = '90f6436b767c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_exam_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('academic_session_id', sa.Integer(), nullable=False),
    sa.Column('exam_number', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_session_id'], ['academic_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'academic_session_id', 'exam_number', name='uq_student_exam_number_school_session_number'),
    sa.UniqueConstraint('student_id', 'school_id', 'academic_session_id', name='uq_student_exam_number_student_school_session')
    )
    with op.batch_alter_table('student_exam_number', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_exam_number_academic_session_id'), ['academic_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_exam_number_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_exam_number_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('other_name', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('other_name')
        batch_op.drop_column('surname')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('student_exam_number', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_exam_number_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_exam_number_school_id'))
        batch_op.drop_index(batch_op.f('ix_student_exam_number_academic_session_id'))

    op.drop_table('student_exam_number')
    # ### end Alembic commands ###
