"""Add school subjects and student enrolment

Revision ID: 2b44d4d94444
Revises: 5a86086b16bc
Create Date: 2026-09-25 07:51:19.641289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b44d4d94444'
down_revision = '5a86086b16bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_subject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_subject_school_id'), ['school_id'], unique=False)

    op.create_table('student_subject_enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('academic_session_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_group_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_session_id'], ['academic_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_group.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['class_id'], ['school_class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['school_subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_subject_enrollment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_subject_enrollment_academic_session_id'), ['academic_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_subject_enrollment_class_group_id'), ['class_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_subject_enrollment_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_subject_enrollment_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_subject_enrollment_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_subject_enrollment_subject_id'), ['subject_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_subject_enrollment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_subject_enrollment_subject_id'))
        batch_op.drop_index(batch_op.f('ix_student_subject_enrollment_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_subject_enrollment_school_id'))
        batch_op.drop_index(batch_op.f('ix_student_subject_enrollment_class_id'))
        batch_op.drop_index(batch_op.f('ix_student_subject_enrollment_class_group_id'))
        batch_op.drop_index(batch_op.f('ix_student_subject_enrollment_academic_session_id'))

    op.drop_table('student_subject_enrollment')
    with op.batch_alter_table('school_subject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_subject_school_id'))

    op.drop_table('school_subject')
    # ### end Alembic commands ###
