"""add school subject selection rule

Revision ID: 3f8358b0426a
Revises: bc042cbe55e5
Create Date: 2026-10-05 22:38:41.417453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8358b0426a'
down_revision = 'bc042cbe55e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_selection_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('minimum_subjects', sa.Integer(), nullable=False),
    sa.Column('maximum_subjects', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subject_selection_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_selection_rule_school_id'), ['school_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject_selection_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_selection_rule_school_id'))

    op.drop_table('subject_selection_rule')
    # ### end Alembic commands ###
