"""Add teacher subject assignments

Revision ID: 49ef530b7669
Revises: 4a051d5e3431
Create Date: 2026-09-25 08:32:02.358778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ef530b7669'
down_revision = '4a051d5e3431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_subject_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('academic_session_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('class_group_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_session_id'], ['academic_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_group.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['class_id'], ['school_class.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['school_subject.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_subject_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_subject_assignment_academic_session_id'), ['academic_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_subject_assignment_class_group_id'), ['class_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_subject_assignment_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_subject_assignment_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_subject_assignment_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_subject_assignment_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_subject_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_subject_assignment_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_subject_assignment_subject_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_subject_assignment_school_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_subject_assignment_class_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_subject_assignment_class_group_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_subject_assignment_academic_session_id'))

    op.drop_table('teacher_subject_assignment')
    # ### end Alembic commands ###
