"""Add school memberships

Revision ID: 4a051d5e3431
Revises: 2b44d4d94444
Create Date: 2026-09-25 08:17:00.507743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a051d5e3431'
down_revision = '2b44d4d94444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('academic_session_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('class_group_id', sa.Integer(), nullable=True),
    sa.Column('membership_type', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_session_id'], ['academic_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_group.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['class_id'], ['school_class.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_membership_academic_session_id'), ['academic_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_membership_class_group_id'), ['class_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_membership_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_membership_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_membership_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_membership_user_id'))
        batch_op.drop_index(batch_op.f('ix_school_membership_school_id'))
        batch_op.drop_index(batch_op.f('ix_school_membership_class_id'))
        batch_op.drop_index(batch_op.f('ix_school_membership_class_group_id'))
        batch_op.drop_index(batch_op.f('ix_school_membership_academic_session_id'))

    op.drop_table('school_membership')
    # ### end Alembic commands ###
