"""add student subject selection workflow

Revision ID: 572cebf3b920
Revises: 3f8358b0426a
Create Date: 2026-10-06 12:35:36.114811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572cebf3b920'
down_revision = '3f8358b0426a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_subject_selection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('academic_session_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_group_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['academic_session_id'], ['academic_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_group.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['class_id'], ['school_class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_subject_selection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_subject_selection_academic_session_id'), ['academic_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_subject_selection_class_group_id'), ['class_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_subject_selection_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_subject_selection_reviewed_by'), ['reviewed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_subject_selection_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_subject_selection_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_subject_selection_student_id'), ['student_id'], unique=False)

    op.create_table('student_subject_selection_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['selection_id'], ['student_subject_selection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['school_subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('selection_id', 'subject_id', name='uq_selection_subject')
    )
    with op.batch_alter_table('student_subject_selection_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_subject_selection_item_selection_id'), ['selection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_subject_selection_item_subject_id'), ['subject_id'], unique=False)

    with op.batch_alter_table('student_subject_enrollment', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_student_subject_enrollment_context', ['student_id', 'school_id', 'academic_session_id', 'class_id', 'class_group_id', 'subject_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_subject_enrollment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_student_subject_enrollment_context', type_='unique')

    with op.batch_alter_table('student_subject_selection_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_subject_selection_item_subject_id'))
        batch_op.drop_index(batch_op.f('ix_student_subject_selection_item_selection_id'))

    op.drop_table('student_subject_selection_item')
    with op.batch_alter_table('student_subject_selection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_subject_selection_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_subject_selection_status'))
        batch_op.drop_index(batch_op.f('ix_student_subject_selection_school_id'))
        batch_op.drop_index(batch_op.f('ix_student_subject_selection_reviewed_by'))
        batch_op.drop_index(batch_op.f('ix_student_subject_selection_class_id'))
        batch_op.drop_index(batch_op.f('ix_student_subject_selection_class_group_id'))
        batch_op.drop_index(batch_op.f('ix_student_subject_selection_academic_session_id'))

    op.drop_table('student_subject_selection')
    # ### end Alembic commands ###
