"""Add school class and academic session structure

Revision ID: 5a86086b16bc
Revises: e1e7a8992f0d
Create Date: 2026-09-25 07:28:53.662477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a86086b16bc'
down_revision = 'e1e7a8992f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('academic_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academic_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_session_school_id'), ['school_id'], unique=False)

    op.create_table('school_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_class_school_id'), ['school_id'], unique=False)

    op.create_table('class_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_class.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_group_class_id'), ['class_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_group_class_id'))

    op.drop_table('class_group')
    with op.batch_alter_table('school_class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_class_school_id'))

    op.drop_table('school_class')
    with op.batch_alter_table('academic_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_session_school_id'))

    op.drop_table('academic_session')
    op.drop_table('school')
    # ### end Alembic commands ###
