"""add net amount & fee

Revision ID: 633a26b2fd66
Revises: 3f80a36f689d
Create Date: 2026-02-18 03:09:38.488948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633a26b2fd66'
down_revision = '3f80a36f689d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.drop_column('net_amount')
        batch_op.drop_column('fee')

    # ### end Alembic commands ###
