"""Add created_at to user

Revision ID: 756a92aa17cc
Revises: 5f335126b21d
Create Date: 2026-02-05 20:48:23.238262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756a92aa17cc'
down_revision = '5f335126b21d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
