"""create assessment attempts and answers

Revision ID: 91eff3c087ad
Revises: 87b4a87d1eee
Create Date: 2026-09-22 09:58:51.820427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91eff3c087ad'
down_revision = '87b4a87d1eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_attempt_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_attempt_student_id'), ['student_id'], unique=False)

    op.create_table('assessment_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('marks_awarded', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('teacher_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_answer_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_answer_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_answer_question_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_answer_attempt_id'))

    op.drop_table('assessment_answer')
    with op.batch_alter_table('assessment_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_attempt_student_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_attempt_assessment_id'))

    op.drop_table('assessment_attempt')
    # ### end Alembic commands ###
