"""add bank_code

Revision ID: 955d3b11b563
Revises: 97d1d5e13164
Create Date: 2026-02-17 23:49:34.744483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955d3b11b563'
down_revision = '97d1d5e13164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('wallet_balance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_code', sa.String(length=10), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('bank_code')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('wallet_balance',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
