"""create withdrawal_requests table

Revision ID: 97d1d5e13164
Revises: 3a1f2c9d6b11
Create Date: 2026-02-16 04:37:40.373585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d1d5e13164'
down_revision = '3a1f2c9d6b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawal_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('account_name', sa.String(length=120), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('paystack_recipient_code', sa.String(length=80), nullable=True),
    sa.Column('paystack_transfer_code', sa.String(length=80), nullable=True),
    sa.Column('paystack_reference', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdrawal_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdrawal_requests_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_rand_key'), ['rand_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_rand_key'))

    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdrawal_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_withdrawal_requests_status'))

    op.drop_table('withdrawal_requests')
    # ### end Alembic commands ###
