"""change referral bonus percentage and amount to numeric

Revision ID: c8a6ad124cdf
Revises: 043cf8cd5aa2
Create Date: 2026-07-06 07:43:15.124067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a6ad124cdf'
down_revision = '043cf8cd5aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("referral_earning", schema=None) as batch_op:
        batch_op.alter_column(
              "amount",
              existing_type=sa.FLOAT(),
              type_=sa.Numeric(precision=12, scale=2),
              existing_nullable=False,
        )

        batch_op.alter_column(
              "created_at",
              existing_type=sa.DATETIME(),
              nullable=False,
        )

        batch_op.create_index(
              batch_op.f("ix_referral_earning_referred_user_id"),
              ["referred_user_id"],
              unique=False,
        )

        batch_op.create_index(
              batch_op.f("ix_referral_earning_referrer_id"),
              ["referrer_id"],
              unique=False,
        )

        batch_op.create_index(
              batch_op.f("ix_referral_earning_subscription_id"),
              ["subscription_id"],
              unique=False,
        )

        batch_op.create_unique_constraint(
              "uq_referral_earning_subscription_id",
              ["subscription_id"],
        )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('wallet_balance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('wallet_balance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)

    with op.batch_alter_table('referral_earning', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_earning_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_referral_earning_referrer_id'))
        batch_op.drop_index(batch_op.f('ix_referral_earning_referred_user_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
