from datetime import datetime

from app.extensions import db


class LessonPlan(db.Model):
    """
    Stores a teacher's lesson plan request and generated lesson content.

    The lesson content is kept separate from the presentation format so
    that additional lesson-plan formats can be introduced later without
    changing the underlying lesson data.
    """

    __tablename__ = "lesson_plan"

    id = db.Column(
        db.Integer,
        primary_key=True
    )

    # ----------------------------------------------------------
    # OWNER
    # ----------------------------------------------------------
    user_id = db.Column(
        db.Integer,
        db.ForeignKey("user.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    user = db.relationship(
        "User",
        backref=db.backref(
            "lesson_plans",
            lazy=True,
            cascade="all, delete-orphan"
        )
    )

    # ----------------------------------------------------------
    # LESSON PLAN FORMAT
    # ----------------------------------------------------------
    # FCT-EMIS is the Version 1.0 default.
    #
    # Future formats can be added without changing the lesson
    # content structure.
    # ----------------------------------------------------------
    format_key = db.Column(
        db.String(50),
        nullable=False,
        default="fct_emis"
    )

    # ----------------------------------------------------------
    # LESSON INFORMATION
    # ----------------------------------------------------------
    lesson_date = db.Column(
        db.Date,
        nullable=True
    )

    class_name = db.Column(
        db.String(100),
        nullable=False
    )

    number_in_class = db.Column(
        db.Integer,
        nullable=True
    )

    average_age = db.Column(
        db.Integer,
        nullable=True
    )

    subject = db.Column(
        db.String(150),
        nullable=False
    )

    lesson_topic = db.Column(
        db.String(255),
        nullable=False
    )

    unit_topic = db.Column(
        db.Text,
        nullable=True
    )

    start_time = db.Column(
        db.String(20),
        nullable=True
    )

    end_time = db.Column(
        db.String(20),
        nullable=True
    )

    duration_minutes = db.Column(
        db.Integer,
        nullable=True
    )

    learning_materials = db.Column(
        db.Text,
        nullable=True
    )

    # ----------------------------------------------------------
    # CURRICULUM / EXAMINATION CONTEXT
    # ----------------------------------------------------------
    curriculum = db.Column(
        db.Text,
        nullable=True
    )

    examination_relevance = db.Column(
        db.String(30),
        nullable=True
    )

    # ----------------------------------------------------------
    # GENERATED CONTENT
    # ----------------------------------------------------------
    # Stored separately from the input fields.
    #
    # This will eventually contain structured lesson-plan data
    # generated by the AI service.
    #
    # We use Text rather than a database-specific JSON type so
    # that the application remains straightforward across
    # SQLite and production databases.
    # ----------------------------------------------------------
    generated_content = db.Column(
        db.Text,
        nullable=True
    )

    status = db.Column(
        db.String(20),
        nullable=False,
        default="draft"
    )

    # ----------------------------------------------------------
    # TIMESTAMPS
    # ----------------------------------------------------------
    created_at = db.Column(
        db.DateTime,
        nullable=False,
        default=datetime.utcnow
    )

    updated_at = db.Column(
        db.DateTime,
        nullable=False,
        default=datetime.utcnow,
        onupdate=datetime.utcnow
    )

    def __repr__(self):
        return (
            f"<LessonPlan {self.id} "
            f"{self.subject} - {self.lesson_topic}>"
        )